=== marcwerenfels/BFH_EXAM_2016/out/xml/fax.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- Defining attributes -->
	<xsd:attribute name="name" type="xsd:string" />
	<xsd:attribute name="faxno">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9 ]*" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="type" default="NORMAL">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="NORMAL" />
				<xsd:enumeration value="URGENT" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="number" type="xsd:positiveInteger" />
	<xsd:attribute name="format" default="A4">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="Letter" />
				<xsd:enumeration value="A4" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="color" default="BW">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="Color" />
				<xsd:enumeration value="BW" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="checksum">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[a-z0-9]*" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="txtime">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9][0-9]:[0-9][0-9](pm|am)" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="txdate">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[1]?[0-9]/[1-3]?[0-9]/[0-9][0-9]" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<!-- Defining complex types -->
	<xsd:complexType name="fromTo">
		<xsd:attribute ref="name" />
		<xsd:attribute ref="faxno" />
	</xsd:complexType>
	<xsd:complexType name="priority">
		<xsd:attribute ref="type" />
	</xsd:complexType>
	<xsd:complexType name="pages">
		<xsd:attribute ref="number" />
		<xsd:attribute ref="format" />
		<xsd:attribute ref="color" />
	</xsd:complexType>
	<xsd:complexType name="checkinfo">
		<xsd:attribute ref="checksum" />
		<xsd:attribute ref="txtime" />
		<xsd:attribute ref="txdate" />
	</xsd:complexType>
	<xsd:complexType name="header">
		<xsd:sequence>
			<xsd:element name="from" type="fromTo" />
			<xsd:element name="to" type="fromTo" />
			<xsd:element name="priority" type="priority" />
			<xsd:element name="pages" type="pages" />
		</xsd:sequence>
	</xsd:complexType>

	<!-- Defining complex elements -->

	<xsd:element name="fax">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="header" type="header" />
				<xsd:element name="body" type="xsd:string" />
				<xsd:element name="checkinfo" type="checkinfo" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== marcwerenfels/BFH_EXAM_2016/out/xml/fax.xml
<?xml version="1.0" encoding="UTF-8"?>
<fax xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	
	xsi:noNamespaceSchemaLocation="./fax.xsd">
  <header>
    <from name="MyCompany" faxno="012 345 67 89"/>
    <to name="YourCompany" faxno="098 765 43 21"/>
    <priority type="URGENT"/>
    <pages number="4" format="Letter" color="BW"/>
  </header>
  <body>
Sehr geehrter Herr Bühler,
Ich habe bei Ihnen gestern per Fax den Artikel 345 bestellt.
Ich möchte diese Bestellung stornieren.

Mit freundlichen Grüssen      Hans Muster
  </body>
  <checkinfo checksum="2af4" txtime="04:35pm" txdate="2/17/07"/>
</fax>
