=== marcwerenfels/BFH_EXAM_2016/out/xml/dom/sonnet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:complexType name="authorType">
		<xsd:sequence>
			<xsd:element name="last-name" type="xsd:string" />
			<xsd:element name="first-name" type="xsd:string" />
			<xsd:element name="nationality" type="xsd:string" />
			<xsd:element name="year-of-birth" type="xsd:unsignedInt" minOccurs="0"/>
			<xsd:element name="year-of-death" type="xsd:unsignedInt"  minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="linesType">
		<xsd:sequence>
			<xsd:element name="line" type="xsd:string" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="sonnet">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="author" type="authorType" />
				<xsd:element name="title" type="xsd:string" />
				<xsd:element name="lines" type="linesType" />
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== marcwerenfels/BFH_EXAM_2016/out/xml/dom/sonnet.xml
<?xml version="1.0" encoding="UTF-8" ?> 
<sonnet type="Shakespearean" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./sonnet.xsd">
  <author>
    <last-name>Shakespeare</last-name> 
    <first-name>William</first-name> 
    <nationality>British</nationality> 
    <year-of-birth>1564</year-of-birth> 
    <year-of-death>1616</year-of-death> 
  </author>
  <title>Sonnet 130</title> 
  <lines>
    <line>My mistress' eyes are nothing like the sun,</line> 
    <line>Coral is far more red than her lips red.</line> 
    <line>If snow be white, why then her breasts are dun,</line> 
    <line>If hairs be wires, black wires grow on her head.</line> 
    <line>I have seen roses damasked, red and white,</line> 
    <line>But no such roses see I in her cheeks.</line> 
    <line>And in some perfumes is there more delight</line> 
    <line>Than in the breath that from my mistress reeks.</line> 
    <line>I love to hear her speak, yet well I know</line> 
    <line>That music hath a far more pleasing sound.</line> 
    <line>I grant I never saw a goddess go,</line> 
    <line>My mistress when she walks, treads on the ground.</line> 
    <line>And yet, by Heaven, I think my love as rare</line> 
    <line>As any she belied with false compare.</line> 
  </lines>
</sonnet>
